version: '3.8'
services:
  nodd-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./local_directory:/local_directory
      - ./credentials/.boto:/root/.boto:ro
      # update vols as needed
      #- ./credentials/.boto:/root/.config/gcloud/.boto:ro
      #- ./credentials/adc.json:/root/.config/gcloud/application_default_credentials.json:ro
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
