version: '3.8'
services:
  nodd-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./local_directory:/local_directory
      - ./credentials/.boto:/root/.boto:ro
    ports:
      - "8501:8501"
