name: 00 - 🧹 Remove Expired Workflow Runs
on:
  #schedule: [{ cron: "30 1 * * *" }] # Schedule to run the workflow every day at 1:30 AM
  workflow_dispatch:

jobs:
  clean:
    name: Remove Expired Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v4

      - name: Run Delete Script
        # run: sh ./00_delete_workflow_runs.sh (your org or github name) (your repo name)
        run: sh ./00_delete_workflow_runs.sh MichaelAkridge-NOAA archive-toolbox
        working-directory: .github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
