name: 05 - Build All Executables

on:
  workflow_dispatch: # Trigger workflow manually from GitHub Actions

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        file: [
          'toolbox/garmin-gps-file-converter/gpxconverter.py',
          'toolbox/archive-manifest-file-tool/mnftool_gui.py'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set file name without extension
        id: set-filename
        run: |
          $fileName = [System.IO.Path]::GetFileNameWithoutExtension("${{ matrix.file }}")
          echo "FILE_NAME=$fileName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "Set FILE_NAME to $fileName"
        shell: pwsh

      - name: Debug - Check FILE_NAME environment variable
        run: echo "FILE_NAME is $env:FILE_NAME"
        shell: pwsh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy gooey

      - name: Build executable
        run: pyinstaller -F --strip --exclude-module tkinter --exclude-module pandas ${{ matrix.file }}

      - name: Debug - List dist directory
        run: dir dist
        shell: pwsh

      - name: Debug - Show FILE_NAME before renaming
        run: echo "Renaming dist/${{ env.FILE_NAME }}.exe to dist/${{ env.FILE_NAME }}-windows.exe"
        shell: pwsh

      - name: Rename artifact
        run: mv dist/${{ env.FILE_NAME }}.exe dist/${{ env.FILE_NAME }}-windows.exe
        shell: pwsh

      - name: Debug - List dist directory after rename
        run: dir dist
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}-windows
          path: dist/${{ env.FILE_NAME }}-windows.zip
