name: 07 - Build All Executables

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest]
        file:
          - toolbox/folder-stats-tool/folderstats.py
          - toolbox/garmin-gps-file-converter/gpxconverter.py

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set file name without extension (Windows)
      if: matrix.os == 'windows-latest'
      id: set-filename-windows
      run: |
        $fileName = [System.IO.Path]::GetFileNameWithoutExtension("${{ matrix.file }}")
        echo "FILE_NAME=$fileName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        echo "Set FILE_NAME to $fileName"
      shell: pwsh

    - name: Set file name without extension (Unix)
      if: matrix.os != 'windows-latest'
      id: set-filename-unix
      run: |
        fileName=$(basename ${{ matrix.file }} .py)
        echo "FILE_NAME=$fileName" >> $GITHUB_ENV
        echo "Set FILE_NAME to $fileName"

    - name: Debug - Check FILE_NAME environment variable
      run: echo "FILE_NAME is ${{ env.FILE_NAME }}"

    - name: Set up Python on Windows and macOS
      if: matrix.os != 'ubuntu-latest'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and pyinstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $file_dir = Split-Path "${{ matrix.file }}"
        python -m pip install --upgrade pip
        pip install -r "$file_dir\\requirements.txt"
        pip install pyinstaller
      shell: pwsh

    - name: Install dependencies and pyinstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        file_dir=$(dirname ${{ matrix.file }})
        python -m pip install --upgrade pip
        pip install -r $file_dir/requirements.txt
        pip install pyinstaller

    - name: Set up Miniconda (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        auto-activate-base: true

    - name: Create and activate conda environment and install pyinstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        conda create -n myenv python=3.11 -y
        conda run -n myenv conda install -c conda-forge pyinstaller wxpython -y
        conda run -n myenv git clone https://github.com/chriskiehl/Gooey.git
        cd Gooey
        conda run -n myenv python setup.py install
        cd ..
        file_dir=$(dirname ${{ matrix.file }})
        if [ -f "$file_dir/requirements.txt" ]; then
          conda run -n myenv pip install -r $file_dir/requirements.txt
        fi`

    - name: Build executable
      run: pyinstaller --onefile "${{ matrix.file }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FILE_NAME }}-${{ matrix.os }}
        path: dist/


  create-release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set release name and tag
      id: set-release
      run: |
        DATE_TIME=$(date +%Y%m%d_%H-%M-%S)
        echo "RELEASE_TAG=v1.0.${DATE_TIME}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Release v1.0.${DATE_TIME}" >> $GITHUB_ENV

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.FILE_NAME }}-${{ matrix.os }}
        path: ./artifacts/

    - name: List downloaded artifacts
      run: ls -R ./artifacts

    - name: Create and Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./artifacts/**/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        body: "Release ${{ env.RELEASE_NAME }} TEST - GHA to build Exe files"
        draft: true
        prerelease: true
