name: v1 Build Windows Executable
on:
  workflow_dispatch: # Trigger workflow manually from GitHub Actions
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy gooey

    - name: Build executable
      run: pyinstaller -F dev/toolbox/garmin-gps-file-converter/gpxconverter.py  # Adjust path if gpxconverter.py is not in the root directory

    - name: Move executable to desired folder
      run: |
        mkdir -p ${{ github.workspace }}/dev/toolbox/garmin-gps-file-converter/dist
        mv dist/gpxconverter.exe ${{ github.workspace }}/dev/toolbox/garmin-gps-file-converter/dist/

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: gpxconverter-executable
        path: dev/toolbox/garmin-gps-file-converter/dist/gpxconverter.exe
