name: Build Linux Exe with PyInstaller
on:
  workflow_dispatch: # Trigger workflow manually from GitHub Actions
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.9'
          auto-activate-base: true

      - name: Create and activate conda environment
        run: |
          conda create -n myenv python=3.9 -y
          conda run -n myenv conda install -c conda-forge pyinstaller numpy wxpython -y

      - name: Install Gooey from source
        run: |
          conda run -n myenv git clone https://github.com/chriskiehl/Gooey.git
          cd Gooey
          conda run -n myenv python setup.py install

      - name: Build executable
        run: |
          conda run -n myenv pyinstaller -F --strip --exclude-module tkinter --exclude-module pandas toolbox/garmin-gps-file-converter/gpxconverter.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gpxconverter-linux
          path: dist/gpxconverter

