name: v2 Build Windows Executable

on:
  workflow_dispatch: # Trigger workflow manually from GitHub Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy gooey

    - name: Build executable
      run: pyinstaller -F --strip --exclude-module tkinter --exclude-module pandas toolbox/garmin-gps-file-converter/gpxconverter.py

    - name: Move executable to desired folder
      run: |
        mkdir -p ${{ github.workspace }}/toolbox/garmin-gps-file-converter/dist
        mv dist/gpxconverter.exe ${{ github.workspace }}/toolbox/garmin-gps-file-converter/dist/
        
    - name: Configure Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Commit and push output files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add toolbox/garmin-gps-file-converter/dist/gpxconverter.exe
        git commit -m 'Add built executable'
        git push

