name: Build Linux Exe with PyInstaller
on:
  workflow_dispatch: # Trigger workflow manually from GitHub Actions

jobs:


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy gooey wxpython>=4.1.0

      - name: Build executable
        run: pyinstaller -F --strip --exclude-module tkinter --exclude-module pandas toolbox/garmin-gps-file-converter/gpxconverter.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gpxconverter-linux
          path: dist/gpxconverter
